create table if not exists accounts (
    account_id varchar(100) not null,
    version bigint not null,
    constraint pk_accounts primary key (account_id)
);

create table if not exists account_balances (
    id bigint generated by default as identity,
    account_id varchar(100) not null,
    asset varchar(20) not null,
    available numeric(30, 12) not null,
    locked numeric(30, 12) not null,
    constraint pk_account_balances primary key (id),
    constraint uk_account_balances_account_asset unique (account_id, asset),
    constraint fk_account_balances_account
        foreign key (account_id) references accounts(account_id),
    constraint ck_account_balances_asset
        check (asset in ('BTC', 'ETH', 'USDT'))
);

create table if not exists orders (
    order_id varchar(100) not null,
    account_id varchar(100) not null,
    base_asset varchar(20) not null,
    quote_asset varchar(20) not null,
    side varchar(20) not null,
    order_type varchar(20) not null,
    status varchar(30) not null,
    price numeric(30, 12),
    qty numeric(30, 12) not null,
    filled_qty numeric(30, 12) not null,
    version bigint not null,
    constraint pk_orders primary key (order_id),
    constraint ck_orders_base_asset
        check (base_asset in ('BTC', 'ETH', 'USDT')),
    constraint ck_orders_quote_asset
        check (quote_asset in ('BTC', 'ETH', 'USDT')),
    constraint ck_orders_side
        check (side in ('BUY', 'SELL')),
    constraint ck_orders_type
        check (order_type in ('MARKET', 'LIMIT')),
    constraint ck_orders_status
        check (status in ('NEW', 'PARTIALLY_FILLED', 'FILLED', 'CANCELLED'))
);

create table if not exists executions (
    execution_id varchar(100) not null,
    order_id varchar(100) not null,
    account_id varchar(100) not null,
    base_asset varchar(20) not null,
    quote_asset varchar(20) not null,
    side varchar(20) not null,
    execution_price numeric(30, 12) not null,
    execution_qty numeric(30, 12) not null,
    quote_amount numeric(30, 12) not null,
    executed_at timestamptz not null,
    constraint pk_executions primary key (execution_id),
    constraint ck_executions_base_asset
        check (base_asset in ('BTC', 'ETH', 'USDT')),
    constraint ck_executions_quote_asset
        check (quote_asset in ('BTC', 'ETH', 'USDT')),
    constraint ck_executions_side
        check (side in ('BUY', 'SELL'))
);

create index if not exists idx_orders_account_id on orders (account_id);
create index if not exists idx_orders_status on orders (status);
create index if not exists idx_executions_order_id on executions (order_id);
create index if not exists idx_executions_account_id on executions (account_id);
create index if not exists idx_account_balances_account_id on account_balances (account_id);