spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cmp?currentSchema=tradecore
    username: cmp
    password: cmp
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: tradecore
    schemas: tradecore

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: tradecore
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true

  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: debug
